AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ImageUri:
    Type: String
    Description: The URI of the container image
  DomainName:
    Type: String
    Default: calendar.kycombinator.com
    Description: Custom domain name for CloudFront

Resources:
  CalendarFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Ref ImageUri
      MemorySize: 1024  # Increased for Next.js app
      Timeout: 30
      Events:
        CloudFrontEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          NODE_ENV: production
      
    Metadata:
      DockerTag: nodejs18
      DockerContext: .
      Dockerfile: Dockerfile

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          TargetOriginId: CalendarAPI
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: true
            Headers:
              - Accept
              - Authorization
              - Referer
            Cookies:
              Forward: all
        Origins:
          - DomainName: !Sub "${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
            Id: CalendarAPI
            OriginPath: ''
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        PriceClass: PriceClass_100  # Use only North America and Europe edge locations
        HttpVersion: http2
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: kycombinator.com.
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront hosted zone ID (constant)

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  
  CloudFrontDomain:
    Description: "CloudFront Distribution Domain Name"
    Value: !GetAtt CloudFrontDistribution.DomainName
  
  CustomDomain:
    Description: "Custom Domain Name"
    Value: !Ref DomainName 