AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ImageUri:
    Type: String
    Description: The URI of the container image
  DomainName:
    Type: String
    Default: calendar.kycombinator.com
    Description: Custom domain name for CloudFront
  CertificateArn:
    Type: String
    Description: The ARN of the ACM certificate

Resources:
  CalendarFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Ref ImageUri
      MemorySize: 1024
      Timeout: 30
      Events:
        CloudFrontEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          NODE_ENV: production
    Metadata:
      DockerTag: nodejs18
      DockerContext: .
      Dockerfile: Dockerfile

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          TargetOriginId: CalendarAPI
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: true
            Headers:
              - Accept
              - Authorization
              - Referer
            Cookies:
              Forward: all
        Origins:
          - DomainName: !Sub "${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com"
            Id: CalendarAPI
            OriginPath: '/Prod'
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        PriceClass: PriceClass_100
        HttpVersion: http2
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  
  CloudFrontDomain:
    Description: "CloudFront Distribution Domain Name"
    Value: !GetAtt CloudFrontDistribution.DomainName